In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [4]:
df['gender'].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [5]:
df['age'].unique()

array([80.  , 54.  , 28.  , 36.  , 76.  , 20.  , 44.  , 79.  , 42.  ,
       32.  , 53.  , 78.  , 67.  , 15.  , 37.  , 40.  ,  5.  , 69.  ,
       72.  ,  4.  , 30.  , 45.  , 43.  , 50.  , 41.  , 26.  , 34.  ,
       73.  , 77.  , 66.  , 29.  , 60.  , 38.  ,  3.  , 57.  , 74.  ,
       19.  , 46.  , 21.  , 59.  , 27.  , 13.  , 56.  ,  2.  ,  7.  ,
       11.  ,  6.  , 55.  ,  9.  , 62.  , 47.  , 12.  , 68.  , 75.  ,
       22.  , 58.  , 18.  , 24.  , 17.  , 25.  ,  0.08, 33.  , 16.  ,
       61.  , 31.  ,  8.  , 49.  , 39.  , 65.  , 14.  , 70.  ,  0.56,
       48.  , 51.  , 71.  ,  0.88, 64.  , 63.  , 52.  ,  0.16, 10.  ,
       35.  , 23.  ,  0.64,  1.16,  1.64,  0.72,  1.88,  1.32,  0.8 ,
        1.24,  1.  ,  1.8 ,  0.48,  1.56,  1.08,  0.24,  1.4 ,  0.4 ,
        0.32,  1.72,  1.48])

In [6]:
df['hypertension'].unique()

array([0, 1])

In [7]:
df['heart_disease'].unique()

array([1, 0])

In [8]:
df['smoking_history'].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [9]:
df['bmi'].unique()

array([25.19, 27.32, 23.45, ..., 59.42, 44.39, 60.52])

In [10]:
df['diabetes'].unique()

array([0, 1])

In [11]:
#age<5
#gender lable
#smoking_history  map

In [12]:
df = df[df['age']>5]

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
lbl = LabelEncoder()

In [15]:
df['gender'] =  lbl.fit_transform(df[['gender']])

In [16]:
df[['gender']]

       gender
0           0
1           0
2           1
3           0
4           1
...       ...
99994       0
99995       0
99997       1
99998       0
99999       0

[93729 rows x 1 columns]

In [17]:
#smoking_history  map

smoking_map = {
    'never': 0,
    'former': 1,
    'not current': 2,
    'current': 3,
    'ever': 2,      # depends on your definition
    'No Info': -1
}

In [18]:
df['smoking_history']= df['smoking_history'].map(smoking_map)

In [19]:
df['smoking_history'].unique()

array([ 0, -1,  3,  1,  2])

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93729 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               93729 non-null  int64
 1   age                  93729 non-null  float64
 2   hypertension         93729 non-null  int64
 3   heart_disease        93729 non-null  int64
 4   smoking_history      93729 non-null  int64
 5   bmi                  93729 non-null  float64
 6   HbA1c_level          93729 non-null  float64
 7   blood_glucose_level  93729 non-null  int64
 8   diabetes             93729 non-null  int64
dtypes: float64(3), int64(6)
memory usage: 7.2 MB

In [21]:
df.duplicated().value_counts()

False    89962
True      3767
Name: count, dtype: int64

In [23]:
df.drop_duplicates(inplace=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89962 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               89962 non-null  int64
 1   age                  89962 non-null  float64
 2   hypertension         89962 non-null  int64
 3   heart_disease        89962 non-null  int64
 4   smoking_history      89962 non-null  int64
 5   bmi                  89962 non-null  float64
 6   HbA1c_level          89962 non-null  float64
 7   blood_glucose_level  89962 non-null  int64
 8   diabetes             89962 non-null  int64
dtypes: float64(3), int64(6)
memory usage: 6.9 MB

In [25]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [28]:
X= df[['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level']]

In [30]:
y =df[['diabetes']]
y

       diabetes
0             0
1             0
2             0
3             0
4             0
...         ...
99993         0
99994         0
99997         0
99998         0
99999         0

[89962 rows x 1 columns]

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
sc = StandardScaler()

In [34]:
X= sc.fit_transform(X)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
reg = LogisticRegression()

In [42]:
reg.fit(X_train,y_train)

LogisticRegression()

In [43]:
reg.predict(sc.transform([[1, 55, 1, 1, 4, 32, 9, 90]]))

array([1])

In [44]:
y_pred = reg.predict(X_test)

In [46]:
y_pred = pd.DataFrame(data=y_pred,columns=['Result'])

In [48]:
result =  pd.concat((y_test.reset_index(drop=True),y_pred.reset_index(drop=True)),axis=1)
result

       diabetes  Result
0             1       0
1             0       0
2             0       0
3             1       1
4             0       0
...         ...     ...
17988         0       0
17989         1       0
17990         0       0
17991         0       0
17992         1       1

[17993 rows x 2 columns]

In [49]:
from  sklearn.metrics import accuracy_score,confusion_matrix

In [51]:
score = accuracy_score(result["diabetes"],result["Result"])
score

0.9565942310898683

In [52]:
cm = confusion_matrix(result["diabetes"],result["Result"])
cm

array([[16094,   177],
       [  604,  1118]])

In [53]:
import pickle as pkl

In [54]:
pkl.dump(reg,open('model.pkl',"wb+"))

In [55]:
pkl.dump(sc,open('scaler.pkl',"wb+"))